[package]
name = "rune_pager"
version = "0.1.0"
authors = ["drwilco"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
serde_json = "1.0.55"
serde = { version = "1.0.111", features = ["derive"] }
phf_codegen = "0.8.0"

[dependencies]
reqwest = { version = "0.10.6", features = ["blocking"] }
regex = "1.3.9"
base64 = "0.12.1"
serde_json = "1.0.55"
serde = { version = "1.0.111", features = ["derive"] }
phf = { version = "0.8.0", features = ["macros"] }
websocket = "0.24.0"
native-tls = "0.2.4"
rusqlite = { version = "0.23.1", features = ["bundled"] }
lazy_static = "1.4.0"
cached = { version = "0.16.0", path = "../cached" }
anyhow = "1.0.31"
