[package]
name = "rune_pager"
version = "0.1.0"
authors = ["drwilco"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.6", features = ["blocking"] }
regex = "1.3.9"
base64 = "0.12.1"
serde_json = "1.0.55"
serde = { version = "1.0.111", features = ["derive"] }
